# Generated by Django 4.2.11 on 2026-03-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='pod_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
