# Generated by Django 5.1.15 on 2026-05-30 03:41

import core.mixins
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_convert_identity_to_fk'),
        ('tasks', '0017_task_secrets_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableAudit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('variable_name', models.CharField(max_length=255)),
                ('variable_scope', models.CharField(choices=[('project', 'Project'), ('shared', 'Shared')], max_length=16)),
                ('vault_path', models.TextField()),
                ('vault_version', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(choices=[('success', 'Success'), ('not_found', 'Not Found'), ('empty', 'Empty'), ('unreachable', 'Unreachable'), ('permission_denied', 'Permission Denied')], max_length=20)),
                ('size_bytes', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField()),
                ('controller_id', models.CharField(max_length=255)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variable_audits', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variable_audits', to='tasks.task')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
            bases=(core.mixins.ProjectScopedModel, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectVariable',
            fields=[
                ('id', models.CharField(default=core.mixins.generate_nanoid, editable=False, max_length=21, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('executor', 'Executor'), ('judge', 'Judge')], max_length=16)),
                ('scope', models.CharField(choices=[('project', 'Project'), ('shared', 'Shared')], default='project', max_length=16)),
                ('description', models.TextField(blank=True, null=True)),
                ('required', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='projects.project')),
            ],
            options={
                'ordering': ['name', 'role'],
                'unique_together': {('project', 'name', 'role')},
            },
            bases=(core.mixins.ProjectScopedModel, models.Model),
        ),
    ]
