services:
  api:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DJANGO_SETTINGS_MODULE=vtaskforge.settings.dev
      - DATABASE_URL=postgres://vtf:vtfdev@db:5432/vtaskforge
      - CELERY_BROKER_URL=redis://redis:6379/0

  db:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vtaskforge
      - POSTGRES_USER=vtf
      - POSTGRES_PASSWORD=vtfdev
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vtf -d vtaskforge"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A vtaskforge worker -l info
    volumes:
      - ./src:/app/src
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DJANGO_SETTINGS_MODULE=vtaskforge.settings.dev
      - DATABASE_URL=postgres://vtf:vtfdev@db:5432/vtaskforge
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A vtaskforge beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./src:/app/src
    depends_on:
      redis:
        condition: service_started
    environment:
      - DJANGO_SETTINGS_MODULE=vtaskforge.settings.dev
      - CELERY_BROKER_URL=redis://redis:6379/0

volumes:
  pgdata:
