{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vtf.redisName" . }}
  labels:
    {{- include "vtf.labels" . | nindent 4 }}
    {{- include "vtf.selectorLabels" (dict "root" . "component" "redis") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vtf.selectorLabels" (dict "root" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vtf.labels" . | nindent 8 }}
        {{- include "vtf.selectorLabels" (dict "root" . "component" "redis") | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
{{- end }}
