{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vtf.redisName" . }}
  labels:
    {{- include "vtf.labels" . | nindent 4 }}
    {{- include "vtf.selectorLabels" (dict "root" . "component" "redis") | nindent 4 }}
spec:
  selector:
    {{- include "vtf.selectorLabels" (dict "root" . "component" "redis") | nindent 4 }}
  ports:
    - port: 6379
      targetPort: 6379
{{- end }}
