apiVersion: v1
kind: Service
metadata:
  name: {{ include "vtf.fullname" . }}-api
  labels:
    {{- include "vtf.labels" . | nindent 4 }}
    {{- include "vtf.selectorLabels" (dict "root" . "component" "api") | nindent 4 }}
spec:
  selector:
    {{- include "vtf.selectorLabels" (dict "root" . "component" "api") | nindent 4 }}
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
