# Generated by Django 5.1.15 on 2026-03-20 08:12

import core.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(default=core.mixins.generate_nanoid, editable=False, max_length=21, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('reviewer_id', models.CharField(max_length=255)),
                ('reviewer_type', models.CharField(choices=[('human', 'Human'), ('agent', 'Agent')], default='human', max_length=10)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tasks.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
