# Generated by Django 5.1.15 on 2026-03-20 07:52

import core.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workplans', '0002_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=core.mixins.generate_nanoid, editable=False, max_length=21, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_start_review', 'Pending Start Review'), ('todo', 'To Do'), ('doing', 'Doing'), ('pending_completion_review', 'Pending Completion Review'), ('changes_requested', 'Changes Requested'), ('needs_attention', 'Needs Attention'), ('blocked', 'Blocked'), ('deferred', 'Deferred'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='draft', max_length=30)),
                ('acceptance_criteria', models.JSONField(blank=True, default=list)),
                ('needs_review_before_start', models.BooleanField(blank=True, default=None, null=True)),
                ('needs_review_on_completion', models.BooleanField(blank=True, default=None, null=True)),
                ('review_return_to', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('requires', models.JSONField(blank=True, default=list)),
                ('assigned_to', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('claimed_by', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('claim_timeout', models.DurationField(blank=True, default=None, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workplans.phase')),
                ('workplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workplans.workplan')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
