# Generated by Django 5.1.15 on 2026-03-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='agent_model',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='isolation',
            field=models.CharField(blank=True, default='sequential', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='judge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='spec',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='test_command',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
