# Generated by Django 5.1.15 on 2026-03-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_agent_model_task_isolation_task_judge_task_spec_and_more'),
        ('workplans', '0003_rename_phase_to_milestone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='phase',
            new_name='milestone',
        ),
        migrations.AlterField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(
                db_column='milestone_id',
                on_delete=models.CASCADE,
                related_name='tasks',
                to='workplans.milestone'
            ),
        ),
    ]
