# Generated by Django 5.1.15 on 2026-03-21 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_phase_to_milestone'),
        ('workplans', '0004_alter_milestone_workplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workplans.milestone'),
        ),
    ]
