# Generated by Django 5.1.15 on 2026-03-21 17:51

import django.db.models.deletion
from django.db import migrations, models


def populate_task_projects(apps, schema_editor):
    """Set task.project from task.workplan.project for all existing tasks."""
    Task = apps.get_model('tasks', 'Task')
    for task in Task.objects.select_related('workplan__project').all():
        if task.workplan and task.workplan.project:
            task.project = task.workplan.project
            task.save(update_fields=['project'])


def reverse_populate_task_projects(apps, schema_editor):
    """No reverse operation needed - projects can stay populated."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0005_alter_task_milestone'),
        ('workplans', '0007_make_project_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workplans.milestone'),
        ),
        migrations.AlterField(
            model_name='task',
            name='workplan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workplans.workplan'),
        ),
        migrations.RunPython(
            populate_task_projects,
            reverse_populate_task_projects,
        ),
    ]
