# Generated by Django 5.1.15 on 2026-03-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_make_project_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='needs_review_on_completion',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
