# Generated by Django 5.1.15 on 2026-03-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_fix_project_cascade_to_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
