# Generated by Django 4.2.11 on 2026-04-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_add_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='execution_summary',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
