# Generated by Django 5.1.15 on 2026-05-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_split_requires_into_required_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='review_expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
