# Generated by Django 5.1.15 on 2026-05-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_review_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='integration_expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_start_review', 'Pending Start Review'), ('todo', 'To Do'), ('doing', 'Doing'), ('pending_completion_review', 'Pending Completion Review'), ('integrating', 'Integrating'), ('changes_requested', 'Changes Requested'), ('needs_attention', 'Needs Attention'), ('blocked', 'Blocked'), ('deferred', 'Deferred'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='draft', max_length=30),
        ),
    ]
