# Generated by Django 5.1.15 on 2026-05-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_task_integration_expires_at_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='secrets_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
