# Generated by Django 5.1.15 on 2026-05-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_task_secrets_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='variables',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
