# Generated by Django 5.1.15 on 2026-03-20 07:49

import core.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.CharField(default=core.mixins.generate_nanoid, editable=False, max_length=21, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('default_needs_review_before_start', models.BooleanField(blank=True, default=None, null=True)),
                ('default_needs_review_on_completion', models.BooleanField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('workplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='workplans.workplan')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
