# Generated by Django 5.1.15 on 2026-03-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplans', '0002_phase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phase',
            new_name='Milestone',
        ),
    ]
