# Generated by Django 5.1.15 on 2026-03-21 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplans', '0003_rename_phase_to_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='workplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='workplans.workplan'),
        ),
    ]
