# Generated by Django 5.1.15 on 2026-03-21 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('workplans', '0004_alter_milestone_workplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workplans', to='projects.project'),
        ),
    ]
