# Generated by Django 5.1.15 on 2026-03-21 17:29

from django.db import migrations


def create_projects_for_workplans(apps, schema_editor):
    """Create a Project for each Workplan and link them."""
    Project = apps.get_model('projects', 'Project')
    Workplan = apps.get_model('workplans', 'Workplan')

    for workplan in Workplan.objects.filter(project__isnull=True):
        # Create a project with the same name and tags as the workplan
        project = Project.objects.create(
            name=workplan.name,
            description=workplan.description,
            tags=workplan.tags or [],
            owner=workplan.owner,
            created_by=workplan.created_by,
        )
        # Link the workplan to the new project
        workplan.project = project
        workplan.save(update_fields=['project'])


def reverse_create_projects_for_workplans(apps, schema_editor):
    """Remove project links and delete auto-created projects."""
    Project = apps.get_model('projects', 'Project')
    Workplan = apps.get_model('workplans', 'Workplan')

    # Remove project links from workplans
    for workplan in Workplan.objects.exclude(project__isnull=True):
        workplan.project = None
        workplan.save(update_fields=['project'])

    # Note: We don't delete the projects as they might have been manually created
    # The admin can delete them manually if needed


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('workplans', '0005_add_project_to_workplan'),
    ]

    operations = [
        migrations.RunPython(
            create_projects_for_workplans,
            reverse_create_projects_for_workplans,
        ),
    ]
