# Generated by Django 5.1.15 on 2026-05-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplans', '0008_convert_identity_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='integration_branch',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
