# Generated by Django 5.1.15 on 2026-03-21 17:21

import core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=core.mixins.generate_nanoid, editable=False, max_length=21, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('repo_url', models.CharField(blank=True, default='', max_length=500)),
                ('default_branch', models.CharField(blank=True, default='main', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
