# Generated by Django 5.1.15 on 2026-05-30 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_convert_identity_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, max_length=63, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Must be a lowercase RFC 1123 label: a-z, 0-9 and internal hyphens only, no leading/trailing hyphen.', regex='^[a-z0-9]([-a-z0-9]*[a-z0-9])?$')]),
        ),
    ]
