# Generated by Django 5.1.15 on 2026-03-20 08:16

import core.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.CharField(default=core.mixins.generate_nanoid, editable=False, max_length=21, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('status_changed', 'Status Changed'), ('claimed', 'Claimed'), ('unclaimed', 'Unclaimed'), ('review_submitted', 'Review Submitted'), ('link_added', 'Link Added'), ('link_removed', 'Link Removed'), ('field_updated', 'Field Updated')], max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.CharField(blank=True, default='', max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tasks.task')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
