# Generated by Django 5.1.15 on 2026-03-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskevent',
            name='event_type',
            field=models.CharField(choices=[('status_changed', 'Status Changed'), ('claimed', 'Claimed'), ('unclaimed', 'Unclaimed'), ('claim_expired', 'Claim Expired'), ('review_submitted', 'Review Submitted'), ('link_added', 'Link Added'), ('link_removed', 'Link Removed'), ('field_updated', 'Field Updated')], max_length=30),
        ),
    ]
