# Generated by Django 4.2.11 on 2026-04-03 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_alter_taskevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='trigger_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='event_type',
            field=models.CharField(choices=[('status_changed', 'Status Changed'), ('claimed', 'Claimed'), ('unclaimed', 'Unclaimed'), ('claim_expired', 'Claim Expired'), ('review_submitted', 'Review Submitted'), ('link_added', 'Link Added'), ('link_removed', 'Link Removed'), ('field_updated', 'Field Updated'), ('force_transition', 'Force Transition'), ('note', 'Note')], max_length=30),
        ),
    ]
