# Generated by Django 4.2.11 on 2026-04-01 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('project', 'Project'), ('workplan', 'Workplan'), ('task', 'Task')], max_length=20)),
                ('resource_id', models.CharField(max_length=50)),
                ('resource_title', models.CharField(max_length=255)),
                ('resource_status', models.CharField(blank=True, default='', max_length=30)),
                ('accessed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['user', '-accessed_at'], name='prefs_recen_user_id_9138d0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='recentaccess',
            constraint=models.UniqueConstraint(fields=('user', 'resource_type', 'resource_id'), name='unique_user_resource_access'),
        ),
    ]
