# Generated by Django 4.2.11 on 2026-04-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('human', 'Human'), ('agent', 'Agent'), ('service', 'Service Account')], default='human', max_length=20),
        ),
    ]
