# Generated by Django 4.2.11 on 2026-04-02 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prefs', '0003_externalidentity_sessionrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=30)),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelProjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('channel_id', models.CharField(max_length=255)),
                ('channel_name', models.CharField(blank=True, default='', max_length=255)),
                ('project_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='channelprojectmapping',
            constraint=models.UniqueConstraint(fields=('provider', 'channel_id'), name='unique_channel_mapping'),
        ),
        migrations.AddField(
            model_name='agentlock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_locks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='agentlock',
            constraint=models.UniqueConstraint(fields=('project_id', 'role'), name='unique_project_role_lock'),
        ),
    ]
