# Generated by Django 5.1.15 on 2026-03-20 08:06

import core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.CharField(default=core.mixins.generate_nanoid, editable=False, max_length=21, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('workplan', 'Workplan'), ('phase', 'Phase'), ('task', 'Task')], max_length=20)),
                ('source_id', models.CharField(max_length=21)),
                ('target_type', models.CharField(max_length=20)),
                ('target_id', models.CharField(max_length=255)),
                ('link_type', models.CharField(choices=[('depends_on', 'Depends On'), ('blocks', 'Blocks'), ('relates_to', 'Relates To'), ('commit', 'Commit'), ('mr', 'Merge Request'), ('area', 'KB Area'), ('doc', 'Document'), ('file', 'File'), ('jira', 'Jira')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='links_link_source__88b29b_idx'), models.Index(fields=['target_type', 'target_id'], name='links_link_target__d3b0ae_idx')],
            },
        ),
    ]
