# Generated by Django 5.1.15 on 2026-03-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='target_type',
            field=models.CharField(max_length=100),
        ),
    ]
