# Generated by Django 5.1.15 on 2026-03-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='source_type',
            field=models.CharField(choices=[('workplan', 'Workplan'), ('milestone', 'Milestone'), ('task', 'Task')], max_length=20),
        ),
    ]
