apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vtf-dev

resources:
  - ../../base
  - ingress.yaml
  - certificate.yaml

images:
  - name: vtf
    newName: harbor.viloforge.com/vafi/vtf
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: vtf-api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: "localhost,127.0.0.1,vtf-api,vtf-api.vtf-dev,vtf-api.vtf-dev.svc.cluster.local,vtf.dev.viloforge.com"
  - target:
      kind: StatefulSet
      name: vtf-db
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
